### ISSUE TITLE
Elsa 2.1.1.463, Multiple Published versions for the same workflow definition

### ISSUE THREAD

**Issue by AvtsVivek** [elsa-workflows/elsa-core#1293]
Sometimes the IsPublished flag is set to true for more than one version of the same workflow definition.

I am using MsSql Server.

![image](https://user-images.githubusercontent.com/41255281/126448599-2497162f-5df4-4bb0-9cca-4aea59ca5056.png)

When ever that happens, I run the workflow and I get the following error.

	{
		"errorMessage": "The call is ambiguous and matches multiple workflows.",
		"workflows": [
			{
				"WorkflowInstanceId": "0cbced1173fa49fb9768d1c7bb093d96",
				"ActivityId": "fe24e264-bcd5-4ca9-b3b1-a1166b3446ea"
			},
			{
				"WorkflowInstanceId": "0611ccc4bb854379a30af28f046d477f",
				"ActivityId": "fe24e264-bcd5-4ca9-b3b1-a1166b3446ea"
			}
		]
	}

I am not able to reproduce this every time. It happens only some times.

The steps to reproduce are as follows.

1. Create a single Http Endpoint activity workflow  as follows. 

![image](https://user-images.githubusercontent.com/41255281/126441953-03089d59-7a63-40ca-83fa-96159ecbef92.png)

![image](https://user-images.githubusercontent.com/41255281/126442232-3d7c8414-3e9f-4169-a3fa-c5e24e524575.png)

2. At this point, the db should show a single version which is not published yet.

![image](https://user-images.githubusercontent.com/41255281/126447644-72eb5061-0ad4-4a8e-a755-a43ccdaff613.png)

3. Now click publish. This will make IsPublished to 1. 
4. Next Edit the Http Activity. You dont have to change any configuration now, just click the save button. Now in the db, there should be two records. 

![image](https://user-images.githubusercontent.com/41255281/126446966-c50c7a35-2bec-4e96-8438-978374ca8b69.png)

5. Now the problem. Click **publish**, run the above query again and observe. 

![image](https://user-images.githubusercontent.com/41255281/126446085-af7375b5-6392-4a62-a487-5918bd665e2f.png)

6. Note the ORDER BY Id and observe Version there. If the version appears in descending order as shown(2 then 1), I see that the bug is reproduced. That is the IsPublished flag will be set to 1 for both the versions. Now I delete the workflow def and start again and if this time, the version appears to be 1 and then 2, then things work correctly. That is, IsPublished is 1 for the latest only. And when I run the workflow, there is no error.

![image](https://user-images.githubusercontent.com/41255281/126450605-f150fad9-389a-43d8-b8f2-d9652bea970d.png)

7. So I repeated this many times, Create, publish, edit-save and then publish. I consistently observed that if the version is 2 and then 1 the problem is reproduced, other wise not. So around 50% of times. Hope you will be able to reproduce this at your end. You can use the same [Elsa.Bug.MultiTenency](https://github.com/AvtsVivek/ElsaBugReports/tree/main/src/Elsa.Bug.MultiTenency) solution that I referred to in [this bug](https://github.com/elsa-workflows/elsa-core/issues/1280) earlier. If used make sure to comment out the following 
                      `     //.AddCustomTenantAccessor<CustomTenantAccessor>()`
in the [startup ](https://github.com/AvtsVivek/ElsaBugReports/blob/102f4c08e5dddbabb878096a2d186140d7ded572/src/Elsa.Bug.MultiTenency/Startup.cs#L51)class.

**Comment by sfmskywalker** [comment]
I think this bug may have been fixed already with #1261, but I'll look into it.

**Comment by sfmskywalker** [comment]
I was able to reproduce the same behavior with your Elsa.Bug.MultiTenenecy project consistently. But after updating the Elsa packages to the latest prerelease versions, the issue went away. I think it's therefore safe to conclude that the issue has been resolved.

If you're still seeing this issue with Elsa 2.2 (prerelease) then please reopen this issue.

Thanks again for the great repro steps.

**Comment by AvtsVivek** [comment]
Ok, I will check it with PreRelease

**Comment by Ethan0007** [comment]
@sfmskywalker this issue still exist on 2.2

![image](https://user-images.githubusercontent.com/12542052/126982113-4bbca964-cbce-44c3-865d-7c7e64ae8c4e.png)

**Comment by sfmskywalker** [comment]
@Ethan0007 This appears to be a different issue than the one described by the OP. Would you mind creating a separate issue for this with repro steps?

**Comment by Ethan0007** [comment]
@sfmskywalker I think it's the same issue, as you can see the error message from my screenshot.

"errorMessage": "The call is ambiguous and matches multiple workflows."

Every time I update the workflow and publish , then calling the same api it will response an error
"errorMessage": "The call is ambiguous and matches multiple workflows."

**Comment by sfmskywalker** [comment]
Ah I see. There could be another reason for that though.

Can you take a look at your workflow definitions in your database, and see if you have multiple versions of the same definition that are both published?

Another reason you are getting this error might be that you have more than one workflow definition using the same HTTP endpoint path.

**Comment by sfmskywalker** [comment]
Also, make sure you didn't already have multiple published versions of the same workflow definition before upgrading to the latest 2.2 preview packages.

**Comment by Ethan0007** [comment]
Yes, every time I publish the workflow it will create another workflow definition with incremented version

![image](https://user-images.githubusercontent.com/12542052/126985830-9e0305e5-e766-41a5-b97d-45f72784e5a2.png)

**Comment by sfmskywalker** [comment]
Sure, but does it also keep these versions with `IsPublished=true`? I can't tell from your screenshot.
If this is the case, is there any chance you can send me your project and database so I can investigate?

**Comment by Ethan0007** [comment]
The problem is two definition id set with IsPublished=true.

![image](https://user-images.githubusercontent.com/12542052/126986335-e718a35b-354f-4051-b5a1-ece586263856.png)

**Comment by sfmskywalker** [comment]
Got it. So can you reproduce this every time with the latest source code or preview packages, even when you first fix the data by setting `IsPublished` to false for version 1?

If so, can you send me your project so I can reproduce this on my machine?

**Comment by Ethan0007** [comment]
I wish I could, but the project is private and confidential.

Hopefully you will understand. :)

**Comment by sfmskywalker** [comment]
Of course, no problem. The challenge is that I am unable to reproduce the issue myself. The OP provided a project using which I was able to repro the problem which I was then able to fix by updating the packages.

If you can setup a new project where you see this same behavior, perhaps by copying your project and removing all of the private and confidential code, and you can still reproduce the bug, then you could send that over to me,

You will understand it's hard to fix a bug that I cannot reproduce.

**Comment by Ethan0007** [comment]
Yep fully understand, I will try to create separate project with the same package and I will let you know.

**Comment by sfmskywalker** [comment]
Much appreciated, thank you.

**Comment by Alhammoud** [comment]
Hi, I get the same issue and I fixed that only to test my custom activity locally by deleting all the records of workflow definition from my database.

**Comment by sfmskywalker** [comment]
@Alhammoud what version are you using?

**Comment by Alhammoud** [comment]
@sfmskywalker Version="2.1.1.463"

**Comment by sfmskywalker** [comment]
@Alhammoud Thanks for the info. The bug was fixed as part of the 2.2 prerelease. If you try to upgrade to it and can still reproduce, please let me know (with repro steps if possible).

**Comment by Andrei-NZ** [comment]
Still present in 2.2. I hit it quite often in my setup (M1 MAC PRO + remote MS SQL) but can't easily/constantly reproduce. Must be some sort of transaction/state issue. Did you need help to nail it or are you on top of this one?

**Comment by sfmskywalker** [comment]
I could use the help, especially from someone who’s able to reproduce some of the time. I have been publishing a lot of workflows, but not once have I reproduced the issue so far.

**Comment by Andrei-NZ** [comment]
Ok, I nailed it, but not sure how to fix properly - I am a couple of days into Elsa and workflows in general :) 

The intermittent issue is due to the WorkflowPublisher.cs and is a result of commit 197db287023031b7d26b2cfc27ccb1efb3ca6860.

On MS SQL
``` C#
var publishedDefinition = await _workflowDefinitionStore.FindByDefinitionIdAsync(
                workflowDefinition.DefinitionId,
                VersionOptions.LatestOrPublished,
                cancellationToken);
```
 generates correct condition

``` SQL
exec sp_executesql N'SELECT TOP(1) [w].[Id], [w].[Data], [w].[DefinitionId], [w].[DeleteCompletedInstances], [w].[Description], [w].[DisplayName], [w].[IsLatest], [w].[IsPublished], [w].[IsSingleton], [w].[Name], [w].[PersistenceBehavior], [w].[Tag], [w].[TenantId], [w].[Version]
FROM [Elsa].[WorkflowDefinitions] AS [w]
WHERE ([w].[DefinitionId] = @__Id_0) AND (([w].[IsPublished] = CAST(1 AS bit)) OR ([w].[IsLatest] = CAST(1 AS bit)))',N'@__Id_0 nvarchar(450)',@__Id_0=N'80bcb3e983f74929bbe8f82f8f91c145'
```

However if we have unpublished (and saved) version of a workflow, which is any workflow which has been altered, but not published i.e.

id | definition id |published | latest |
| :------------- |:-------------|:-------------:| :-----:|
1ae2c2eaa93347e4974af729393e900c | 80bcb3e983f74929bbe8f82f8f91c145 | 1 | 0 |
006c21b56b1e40f785aae0180ff31985 | 80bcb3e983f74929bbe8f82f8f91c145 | 0 | 1 |

In this scenario, two records will match the OR condition.

Without ORDER BY, MS SQL will return records in random order, [see here](https://stackoverflow.com/questions/10064532/the-order-of-a-sql-select-statement-without-order-by-clause)

In the example above, the order used seems to be ascending PK, resulting in the latest record to be on top, because the unpublished GUID starts with '0' which is less than '1'.

As result the reset is executed on the latest workflow and not the last published.

``` C#
  if (publishedDefinition != null)
            {
                publishedDefinition.IsPublished = false;
                publishedDefinition.IsLatest = false;
                await _workflowDefinitionStore.SaveAsync(publishedDefinition, cancellationToken);
            }
```

So we have a regression bug. We'd need to rollback #1261 and fix the issue addressed by #1261 differently.
Should probably also add a safeguard where if retrieving a single entity yields multiple entities, a Warning is logged in the console, or something... 

SQl trace to prove the above:

``` SQl
exec sp_executesql N'SELECT TOP(1) [w].[Id], [w].[Data], [w].[DefinitionId], [w].[DeleteCompletedInstances], [w].[Description], [w].[DisplayName], [w].[IsLatest], [w].[IsPublished], [w].[IsSingleton], [w].[Name], [w].[PersistenceBehavior], [w].[Tag], [w].[TenantId], [w].[Version]
FROM [Elsa].[WorkflowDefinitions] AS [w]
WHERE ([w].[DefinitionId] = @__Id_0) AND (([w].[IsPublished] = CAST(1 AS bit)) OR ([w].[IsLatest] = CAST(1 AS bit)))',N'@__Id_0 nvarchar(450)',@__Id_0=N'80bcb3e983f74929bbe8f82f8f91c145'

exec sp_executesql N'SELECT TOP(1) [w].[Id], [w].[Data], [w].[DefinitionId], [w].[DeleteCompletedInstances], [w].[Description], [w].[DisplayName], [w].[IsLatest], [w].[IsPublished], [w].[IsSingleton], [w].[Name], [w].[PersistenceBehavior], [w].[Tag], [w].[TenantId], [w].[Version]
FROM [Elsa].[WorkflowDefinitions] AS [w]
WHERE [w].[Id] = @__p_0',N'@__p_0 nvarchar(450)',@__p_0=N'006c21b56b1e40f785aae0180ff31985'

exec sp_executesql N'SET NOCOUNT ON;
UPDATE [Elsa].[WorkflowDefinitions] SET [IsLatest] = @p0
WHERE [Id] = @p1;
SELECT @@ROWCOUNT;

',N'@p1 nvarchar(450),@p0 bit',@p1=N'006c21b56b1e40f785aae0180ff31985',@p0=0
```

**Comment by sfmskywalker** [comment]
As chance would have it, I was running into this very same issue this morning myself. Your findings are spot-on. The best way to fix it is by retrieving ALL published versions of a workflow (in theory there should only ever be one, but sets affected by this bug would then auto-heal).

To mitigate the bug that was fixed with 197db287023031b7d26b2cfc27ccb1efb3ca6860, we not only take latest or published, but latest AND published. 

I will push a fix.

Thanks for the detailed findings, this explained a lot!
