### ISSUE TITLE
Elsa 2.0 Deployment issue

### ISSUE THREAD

**Issue by VivekKachare007** [elsa-workflows/elsa-core#1395]
When I import the necessary packages for Elsa 2.0 Dashboard + server and run it at local IIS Express it works absolutely fine. But when I deploy the solution all the references used in _Host.cshtml are lost.
![Capture](https://user-images.githubusercontent.com/89069088/129705080-eb316af7-62d6-4cd8-a922-68b9b71bdc76.PNG)
![Capture](https://user-images.githubusercontent.com/89069088/129705146-27ce60d2-cb89-4048-a43b-7609a021f78b.PNG)

Is there any step that I have missed on.

**Comment by matt4446** [comment]
check you've added to the statup.cs:
`services.AddElsaApiEndpoints();`

https://elsa-workflows.github.io/elsa-core/docs/next/quickstarts/quickstarts-aspnetcore-server-dashboard-and-api-endpoints#startup

**Comment by VivekKachare007** [comment]
![Capture](https://user-images.githubusercontent.com/89069088/129727903-1d53eed6-9132-4bfc-8af8-1879d5cde95d.PNG)
Yes I have included the same in startup.cs

**Comment by rairafaqatali** [comment]
Can you check that you have got the server url dynamically in code, check the below code:
`@page "/"
@{
    var serverUrl = $"{Request.Scheme}://{Request.Host}";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Elsa Workflows</title>
    <link rel="icon" type="image/png" sizes="32x32" href="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-16x16.png">
    <link rel="stylesheet" href="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/fonts/inter/inter.css">
    <link rel="stylesheet" href="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.css">
    <script src="/_content/Elsa.Designer.Components.Web/monaco-editor/min/vs/loader.js"></script>
    <script type="module" src="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.esm.js"></script>
</head>
<body>
    <elsa-studio-root server-url="@serverUrl" monaco-lib-path="_content/Elsa.Designer.Components.Web/monaco-editor/min">
        <elsa-studio-dashboard></elsa-studio-dashboard>
    </elsa-studio-root>
</body>
</html>`

**Comment by matt4446** [comment]
is it set up for HTTPS? I can the request is made to HTTP://localhost

**Comment by VivekKachare007** [comment]
![image](https://user-images.githubusercontent.com/89069088/130408554-f952417e-a154-44a0-9e33-075c3cee2b1a.png)
base url


![image](https://user-images.githubusercontent.com/89069088/130408722-cc783500-293a-44d7-b07b-7a073dfda0b8.png)
host.cshtml

![image](https://user-images.githubusercontent.com/89069088/130409031-3fb16446-8b47-457c-81c2-f72b2dca1227.png)
after hosting its not taking http://localhost/elsa24 

any change I need to do so that the application picks the right path

**Comment by VivekKachare007** [comment]
Just for some additional information I have deployed the applicatin under default web site 
![image](https://user-images.githubusercontent.com/89069088/130487662-eb956351-adfd-4327-b973-266f9357ba2a.png)

**Comment by matt4446** [comment]
Ah so its running as a virtual directory application rather than a site. I think there was another post somewhere for the same problem but I wasn't following the outcome (I have not run a virtual applications since 2009~ so not the best to help with that). Does it need to run as a virtual application or can it just run as 'the' localhost website (default web site)? or as simply create a new website and bind localhost to a new port 

Worth a try: 
Add `app.UsePathBase("/elsa24")` into the startup.cs
Add `<base href="~/elsa24/" />` into _host.cshtml

**Comment by VivekKachare007** [comment]
![image](https://user-images.githubusercontent.com/89069088/130618682-aeea87b1-e6e3-4511-917c-d99a385dae58.png)
I am still getting the same error

**Comment by matt4446** [comment]
Isn't this the same setup as `defaultwebsite` + virtual app folders? but with `dashboard-dev2` + "Elsa Dashbaord 2" in this case.  

Have you tried dropping the virtual app folders and simply running it as a website first. Any reason you need them?
Back to basics: `http://dashboard-dev2/` 

Those error 500's were probably getting close to a solution. You would need to check the logs to see why its failing. Event Viewer maybe.

**Comment by VivekKachare007** [comment]
http://dashboard-dev2/ElasDashboard2 
In this the server name is Dashboard-Dev2 and ElsaDashboard2 is the application under default web site

**Comment by sfmskywalker** [comment]
Here are the steps that worked for me:

1. Make sure you are using the latest Elsa Dashboard package (2.3.x preview from MyGet to be safe, but if that works and you need 2.2.x then feel free to try that one as well).
2. Update your _Host.cshtml file as follows:

```html
@page "/"
@inject IConfiguration Configuration;
@{
    var serverUrl = Configuration["Elsa:Server:BaseAddress"];
    var basePath = Configuration["Hosting:BasePath"];
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Elsa Workflows</title>
    <link rel="icon" type="image/png" sizes="32x32" href="@basePath/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="@basePath/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-16x16.png">
    <link rel="stylesheet" href="@basePath/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/fonts/inter/inter.css">
    <link rel="stylesheet" href="@basePath/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.css">
    <script src="@basePath/_content/Elsa.Designer.Components.Web/monaco-editor/min/vs/loader.js"></script>
    <script type="module" src="@basePath/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.esm.js"></script>
</head>
<body>
<elsa-studio-root server-url="@serverUrl" base-path="@basePath" monaco-lib-path="@basePath.TrimStart('/')/_content/Elsa.Designer.Components.Web/monaco-editor/min">
    <elsa-studio-dashboard></elsa-studio-dashboard>
</elsa-studio-root>
</body>
</html>
```

Notice the addition of the `basePath` variable which is read from configuration. We will be setting this from IIS as an environment variable to the following value: `\ElsaDashoard` (the virtual directory I am using for this example).

Notice also that I'm setting this `basePath` value to the `base-path` attribute on the `elsa-studio-root` element and also use it as a prefix for all of the included resources (scripts and styles).

Another important part is to trim sway the starting slash for the monaco path. This is kind of a rough edge that I might get to improve eventually, but for now a simple `@basePath.TrimStart('/')` will suffice.

3. Configure your IIS virtual directory / application as follows:

![image](https://user-images.githubusercontent.com/938393/133144608-f373d8ab-4a10-4302-b13c-a07248d03763.png)

When you deploy these changes to IIS (`dotnet publish -f net5.0`) and restart the site then you should see the resources are now loaded correctly:

![image](https://user-images.githubusercontent.com/938393/133144857-ce6f6b01-e971-456c-ab5d-ae70e37f4331.png)

With that, the dashboard now works when served from the **ElsaDashboard** IIS application directory:

![image](https://user-images.githubusercontent.com/938393/133145704-3fe93656-b688-4b08-a981-c9724fea0f61.png)

**Comment by Marsland** [comment]
Note that some may need to explicitly denote the namespace for IConfiguration in the _Host.cshtml page:
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;

**Comment by jayachandra21** [comment]
Dear @sfmskywalker,

Thanks for the information & steps to resolve this issue.
Even  I am facing the same issue, and I have tried with the steps you have provided as above.

However I am facing an issue to load the Elsa portal and no action is happening when click on the buttons in main page.

![image](https://user-images.githubusercontent.com/67507118/133970714-34f1db97-78cf-4e83-983e-0e95f2f30978.png)

Browser view source code:
![image](https://user-images.githubusercontent.com/67507118/133971849-391906d5-4ac1-4792-9bc1-7327acfda0ac.png)

**Steps I have performed is as,**
1. _Host.cshtml 
```@page "/"
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;
@{
    var serverUrl = Configuration["Elsa:Server:BaseUrl"];
    var basePath = Configuration["Hosting:BasePath"];
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Elsa Workflows</title>
    <link rel="icon" type="image/png" sizes="32x32" href="@basePath/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="@basePath/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-16x16.png">
    <link rel="stylesheet" href="@basePath/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/fonts/inter/inter.css">
    <link rel="stylesheet" href="@basePath/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.css">
    <script src="@basePath/_content/Elsa.Designer.Components.Web/monaco-editor/min/vs/loader.js"></script>
    <script type="module" src="@basePath/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.esm.js"></script>
</head>
<body>
    <elsa-studio-root server-url="@serverUrl" base-path="@basePath" monaco-lib-path="@basePath.TrimStart('/')/_content/Elsa.Designer.Components.Web/monaco-editor/min">
        <elsa-studio-dashboard></elsa-studio-dashboard>
    </elsa-studio-root>
</body>
</html>
```
2. appsettings.json
```{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "WorkflowDB": "Data Source=localhost;Initial Catalog=Else21;User ID=sa;Password=password"
  },
  "Elsa": {
    "Server": {
      "BaseUrl": "http://workflow-test:80/"
    }
  },
  "Hosting": {
    "BasePath": "/ElsaDashboard"
  }
}
```
3. Configured IIS virtual directory / application as follows:
![image](https://user-images.githubusercontent.com/67507118/133971386-917bbc14-41fa-433e-b28d-e57ea1879bb3.png)

Please guide if I have missed any configuration.

**Comment by mohdali** [comment]
Hi @sfmskywalker ,

I managed to get the links working after some tweaks. However, I noticed that the link for Instances under workflow definitions is not using the base path. Same link under registry is working fine.

![image](https://user-images.githubusercontent.com/4145465/134038198-59fc4626-a0fd-47d7-b3ae-0af750ee582b.png)


I'm using version 2.2.1, is it fixed in the 2.3-preview?

**Comment by sfmskywalker** [comment]
Might be an omission on my part, will check.

**Comment by Marsland** [comment]
I can confirm I'm seeing the same behavior in my test install of Dashboard.

**Comment by sfmskywalker** [comment]
@jayachandra21 Perhaps the issue is that your workflow server (assuming that's hosted separately given your `server-url` attribute pointing to `https://workflow-test:80` is not properly running? If you open the console window in your browser, you're likely to see some some errors. If so, please share them here so we might see what's going on.

**Comment by sfmskywalker** [comment]
@mohdali It was indeed an omission. I just pushed a fix that should now use the correct path.

**Comment by guyansrg** [comment]
@sfmskywalker [ver: 2.3.0] After setting BasePath, there is something wrong with the Pager component in Workflow Instances page.

![image](https://user-images.githubusercontent.com/26474218/136644169-8c02d8e1-87ce-41aa-ae42-cc74ac3d4488.png)

It can be fixed by modifying the following code.

![image](https://user-images.githubusercontent.com/26474218/136644779-4002a7a8-5dd2-4540-99d1-42dd9c068ef5.png)

**Comment by sfmskywalker** [comment]
Hi @andreapier. The fact that it fails on the `/features` endpoint makes me believe that the issue may be solved when upgrading to the latest 2.6-preview release from MyGet. Perhaps you can give that a try and let me know?

**Comment by andreapier** [comment]
> Hi @andreapier. The fact that it fails on the `/features` endpoint makes me believe that the issue may be solved when upgrading to the latest 2.6-preview release from MyGet. Perhaps you can give that a try and let me know?

Hi, I just tried again using v2.6.0 and it is still not working. Same error

**Comment by sfmskywalker** [comment]
OK. Thanks for checking.

**Comment by andreapier** [comment]
Has this been solved? I believe that installing Elsa in a subdirectory is something that is pretty common

**Comment by andreapier** [comment]
> OK. Thanks for checking.

Sorry, I was wrong. It works. I just missed the final `/` in `Elsa:Server:BaseUrl` 🤦 
This is the relevant configuration to serve the editor from a sudirectory:

`appsettings.json`
```json
...
"Elsa": {
    "Server": {
      "BaseUrl": "http://localhost/workflow-server/"
    }
  },
  "Hosting": {
    "BasePath": "/workflow-server"
  },
...
```

`_Host.cshtml`
```html
@page "/"

@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;

@{
    var serverUrl = Configuration["Elsa:Server:BaseUrl"];
    var basePath = Configuration["Hosting:BasePath"];
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Elsa Workflows</title>
    <link rel="icon" type="image/png" sizes="32x32" href="@basePath/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="@basePath/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-16x16.png">
    <link rel="stylesheet" href="@basePath/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/fonts/inter/inter.css">
    <link rel="stylesheet" href="@basePath/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.css">
    <script src="@basePath/_content/Elsa.Designer.Components.Web/monaco-editor/min/vs/loader.js"></script>
    <script type="module" src="@basePath/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.esm.js"></script>
</head>
<body>
    <elsa-studio-root server-url="@serverUrl" base-path="@basePath" monaco-lib-path="@basePath.TrimStart('/')/_content/Elsa.Designer.Components.Web/monaco-editor">
        <elsa-studio-dashboard></elsa-studio-dashboard>
    </elsa-studio-root>
</body>
</html>
```

`Startup.cs`
```csharp
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    ...
    // app.UseAuthentication(); //if needed

    app
        .UseStaticFiles()
        .UseRouting();
   // app.UseAuthorization();//if needed
   ....
}
```

**Comment by sfmskywalker** [comment]
Tricky business, these paths with trailing slashes 😄 
Glad you figured it out!

**Comment by lakuri** [comment]
@sfmskywalker  Why is the `Hosting` not inside the `Elsa`?
```...
"Elsa": {
    "Server": {
      "BaseUrl": "http://workflow-test:80/"
    }
  },
  "Hosting": {
    "BasePath": "/ElsaDashboard"
  }
...
```

Can't it be 
```...
"Elsa": {
    "Server": {
      "BaseUrl": "http://workflow-test:80/"
    }
    "Hosting": {
       "BasePath": "/ElsaDashboard"
   }
  },
...
```

**Comment by sfmskywalker** [comment]
The main reason is that the "Hosting" part is not a specific thing to Elsa, but more about how you chose to setup your application. Putting it into the "Elsa" section, however, that's perfectly fine if that has your preference.

**Comment by sfmskywalker** [comment]
Closing as stale because this thread is about hosting the legacy Elsa 2 dashboard from `elsa-core` under IIS virtual directories. That UI stack is no longer the actively developed surface, so I am not keeping old dashboard-hosting backlog items open here.
