### ISSUE TITLE
FlowJoin with WaitAll mode not wating

### ISSUE THREAD

**Issue by SaberRajabi1990** [elsa-workflows/elsa-core#6725]
The FlowJoin with WaitAll mode is not behaving as expected. When there is a loop in one of the branches, the other branch does not wait properly. The previous bookmark is removed, and the running activity gets canceled. What is the recommended way to implement parallel branches with loopbacks in a Flowchart?

this is my code:

`				new(new Endpoint(join), new Endpoint(fork)),
				new Connection(new Endpoint(fork, "report"), new Endpoint(employeeMissionReportActivity)),
				new Connection(new Endpoint(employeeMissionReportActivity), new Endpoint(supervisorMissionReportApprovalActivity)),
				new Connection(new Endpoint(supervisorMissionReportApprovalActivity), new Endpoint(handleSupervisorMissionReportApprovalActivity)),
				new Connection(new Endpoint(handleSupervisorMissionReportApprovalActivity, "True"), new Endpoint(managerMissionReportApprovalActivity)),
				new Connection(new Endpoint(handleSupervisorMissionReportApprovalActivity, "False"), new Endpoint(employeeMissionReportActivity)), 
				
				new(new Endpoint(managerMissionReportApprovalActivity), new Endpoint(handleManagerMissionReportApprovalActivity)),

				new Connection(new Endpoint(handleManagerMissionReportApprovalActivity, "True"), new Endpoint(joinReportAndCost)),
				new Connection(new Endpoint(handleManagerMissionReportApprovalActivity, "False"), new Endpoint(employeeMissionReportActivity)),
	
				// Cost Branch
				new Connection(new Endpoint(fork, "cost"), new Endpoint(employeeMissionExpenseActivity)),
				new Connection(new Endpoint(employeeMissionExpenseActivity), new Endpoint(supervisorMissionExpenseApprovalActivity)),
				new Connection(new Endpoint(supervisorMissionExpenseApprovalActivity), new Endpoint(handleSupervisorMissionExpenseApprovalActivity)),
				new Connection(new Endpoint(handleSupervisorMissionExpenseApprovalActivity, "True"), new Endpoint(managerMissionExpenseApprovalActivity)),
				new Connection(new Endpoint(handleSupervisorMissionExpenseApprovalActivity, "False"), new Endpoint(employeeMissionExpenseActivity)),

				new(new Endpoint(managerMissionExpenseApprovalActivity), new Endpoint(handleManagerMissionExpenseApprovalActivity)),

				new Connection(new Endpoint(handleManagerMissionExpenseApprovalActivity, "True"), new Endpoint(joinReportAndCost)),
				new Connection(new Endpoint(handleManagerMissionExpenseApprovalActivity, "False"), new Endpoint(employeeMissionExpenseActivity)),
	
				new Connection(new Endpoint(joinReportAndCost), new Endpoint(checkReportAndExpenseApprovalActivity)),`

**Comment by sfmskywalker** [comment]
Which version is this?

**Comment by SaberRajabi1990** [comment]
version 3.4.0

**Comment by SaberRajabi1990** [comment]
Please help!
I have spent a month learning and implementing my project using the Elsa 3 library and I’m currently under a lot of pressure. What alternative approaches can I use to implement my scenario?
both branches have to finish then join and go to next stetp

![Image](https://github.com/user-attachments/assets/ff360a12-f3a7-4e13-9615-9cfdfae826a2)

**Comment by sfmskywalker** [comment]
Is this the same issue or a different one?

**Comment by sfmskywalker** [comment]
Yeah, that does sound very familiar, so it should be solved with 3.6.
To confirm, you should try the 3.6. preview. Keep in mind that some packages have been renamed, like Elsa.EntityFrameworkCore -> Elsa.Persistence.EFCore.

There are probably some other changes, but if you could try on a separate branch to not lose existing work in case there are too many breaking issues.

Or, as already proposed, I'd be happy to confirm it has been fixed if you can provide me with a repro.

**Comment by sfmskywalker** [comment]
That's really hard to say due to the dynamic and organic nature of this OSS project. That said, I am aiming for somewhere in August.

**Comment by SaberRajabi1990** [comment]
I apologize for taking your time. But could you suggest a way for me to send them to join after ensuring that both branches are finished? For example, by defining a variable to indicate the end of both branches. Should I create a bookmark after assigning a value to this variable?

**Comment by sfmskywalker** [comment]
One thing you could try is to disconnect the last activity, I.e., removing the join. Instead, end both branches with their own SetVariable and Publish Event activity. The SetVariable activities set some variable, either one per branch, or a single variable of type Int32 that gets incremented. Then add a single new Event activity without any inbound connections, effectively starting a disconnected path, and connect that to a new Decision activity. This Decision activity must then check for the branch variables to see if the are set, and if so, its True outcome will trigger, which you connect to the activity into which you were joining the two branches.

When configuring the PublishEvent activities, use the same event name, e.g., “BranchCompleted” and tick the “Local Event” checkbox to bind the event to the current workflow instance.

When configuring the Event activity, make sure that it listens for the “BranchCompleted” event and make sure that the”Trigger Workflow” checkbox is *unchecked*, because you want this activity to not trigger new workflows.

**Comment by popescumadalin0** [comment]
![Image](https://github.com/user-attachments/assets/05a0a082-434b-4f73-99f9-3b632411711c)

![Image](https://github.com/user-attachments/assets/322893d0-92c9-4249-9ec4-f098f815cb34)

Hey guys! I have updated the Elsa packages to the latest preview for v3.6.0, and it still does not work (merge mode is converge)

**Comment by SaberRajabi1990** [comment]
I worked around this bug by defining a numeric variable and incrementing its value right before the point where the join is supposed to happen. Immediately after this activity, I added another activity to check that number. If both branches reach the expected value, I proceed to the join step. It seems to be working correctly, but I’m not completely sure yet.

`	protected override async void Execute(ActivityExecutionContext context)
	{

		int newVal = context.GetVariable<int>("CompletedBranches") + 1;
		context.SetVariable("CompletedBranches", newVal);
	}


	[FlowNode("True", "False")]
	public class IsBrancheTwoFinishedDecisionActivity : Activity
	{		
		protected override async ValueTask ExecuteAsync(ActivityExecutionContext context)
		{		
			int cmpletedBranches = context.GetVariable<int>("CompletedBranches");
			var outcome = cmpletedBranches == 2 ? "True" : "False";
			await context.CompleteActivityWithOutcomesAsync(outcome);
		}
	}

         new Connection(new Endpoint(expenseBranchChecker), new Endpoint(isBrancheTwoFinishedDecisionActivity)),
	new Connection(new Endpoint(isBrancheTwoFinishedDecisionActivity, "True"), new Endpoint(joinReportAndCost)),
`
